apiVersion: v1
kind: Pod
metadata:
  name: falco-event-listener
  namespace: falco
  labels:
    app: falco-event-listener
spec:
  containers:
  - image: ko://github.com/developer-guy/falco-event-listener
    name: falco-event-listener
    args:
      - "--owner"
      - "developer-guy"
      - "--repository"
      - "pwned-desired-state-repository"
      - "--file"
      - "alpine.yaml"
      - "--github-token"
      - "$(GITHUB_TOKEN)"
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-secret
            key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: falco-event-listener
  name: falco-event-listener
  namespace: falco
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: falco-event-listener
  type: ClusterIP
